package:
  name: maast
  version: 1.0.8

source:
  git_url: https://github.com/zjshi/Maast.git

requirements:
  build:
    - python ==3.9.6
    - {{ compiler('cxx') }}
    - setuptools
    - pip
  host:
    - python ==3.9.6
    - setuptools
    - pip
    - numpy
    - scipy 
    - biopython
    - networkx 
  run:
    - python ==3.9.6
    - pip
    - numpy
    - scipy 
    - networkx
    - biopython
    - fasttree
    - mash
    - mummer4
    - pigz
    - lz4
    - lbzip2

test:
   import:
    - numpy
    - scipy 
    - biopython
    - networkx 

about:
  home: https://github.com/zjshi/Maast
  license: MIT License
  license_file: LICENSE
  summary: Maast for efficient genotyping of microbial SNPs
  doc_url: https://github.com/zjshi/Maast
  dev_url: https://github.com/zjshi/Maast
